[tool.poetry]
name = "new-course4"
version = "0.1.0"
description = ""
authors = ["Pavel Novikov <ya@pnovik.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
